package de.farmpulse.rpsim.narration;

/**
 * Every event the personality layer can narrate. Each type has a fallback template
 * (fallback-templates/{locale}/{TYPE}.txt) so the game stays fully playable without a working AI.
 */
public enum NarrationEventType {
    // onboarding / story
    ONBOARDING_WELCOME,
    STORY_HOOK,
    // credit
    CREDIT_APPROVED,
    CREDIT_COUNTER_OFFER,
    CREDIT_REJECTED,
    CREDIT_PAYMENT_REMINDER,
    CREDIT_PENALTY,
    CREDIT_TRUST_WARNING,
    CREDIT_CALLBACK,
    CREDIT_BLOCKED,
    CREDIT_DEFERRAL_GRANTED,
    CREDIT_DEFERRAL_DENIED,
    CREDIT_SPECIAL_REPAYMENT,
    CREDIT_PAID_OFF,
    // Roadmap V2 R2-B5: real farm finances
    BANK_CASHFLOW_WARNING,
    COOPERATIVE_RECORD_HARVEST,
    // Roadmap V2 R2-A: employees as FS25 helpers
    EMPLOYEE_STRIKE,
    EMPLOYEE_STRIKE_ENDED,
    MECHANIC_REPORT,
    ANIMAL_KEEPER_WARNING,
    VET_EMERGENCY,
    // Roadmap V2 R2-C: fields, crops and weather
    FIELD_NEIGHBOR_COMPLAINT,
    FIELD_GOSSIP,
    FIELD_HARVEST_CONGRATULATION,
    FIELD_WORK_HINT,
    // Roadmap V2 R2-D: the vanilla loan and the field menu become part of the story
    VANILLA_LOAN_TAKEN,
    VANILLA_LOAN_REPAID,
    FIELD_BOUGHT_OVER_HEAD,
    COMPENSATION_SETTLED,
    COMPENSATION_DISPUTE,
    OUTSIDE_HELPERS_HINT,
    // Roadmap V2 R2-E1: tax office and tax advisor
    TAX_PREPAYMENT,
    TAX_ASSESSMENT,
    TAX_REMINDER,
    TAX_ENFORCEMENT,
    TAX_AUDIT_ANNOUNCED,
    TAX_AUDIT_RESULT,
    TAX_ADVISOR_OFFER,
    TAX_ADVISOR_REMINDER,
    // Roadmap V2 R2-E2: authority
    AUTHORITY_ROTATION_NOTICE,
    AUTHORITY_SUBSIDY,
    AUTHORITY_INSPECTION_NOTICE,
    AUTHORITY_INSPECTION_RESULT,
    // Roadmap V2 R2-E3: family
    FAMILY_OCCASION,
    FAMILY_FIELD_SOLD,
    FAMILY_HARVEST_HELP,
    // Roadmap V2 R2-E4: clubs and festivals
    SPONSORING_REQUEST,
    SPONSORING_THANKS,
    // market
    MARKET_PRICE_EVENT,
    MARKET_SPECIAL_OFFER,
    MARKET_SUBSIDY,
    MARKET_RUMOR,
    MARKET_CONTRACT_ENDED,
    // negotiation
    AUCTION_ANNOUNCED,
    NEGOTIATION_ACCEPTED,
    NEGOTIATION_COUNTER,
    NEGOTIATION_REJECTED,
    AUCTION_WON,
    AUCTION_LOST,
    SALE_OFFER_RECEIVED,
    SALE_NO_INTEREST,
    // employees
    JOB_APPLICATION,
    INTERVIEW_ANSWER,
    APPLICATION_REJECTED,
    EMPLOYEE_WELCOME,
    EMPLOYEE_THANKS,
    EMPLOYEE_WARNING,
    EMPLOYEE_RESIGNATION,
    EMPLOYEE_SALARY_OVERDUE,
    // village life
    VILLAGE_CONGRATULATION,
    VILLAGE_INVITATION,
    VILLAGE_GOSSIP,
    // characters
    CHARACTER_FAREWELL,
    CHARACTER_INTRODUCTION,
    ABSENCE_NOTICE,
    SUBSTITUTE_INTRODUCTION,
    // insurance (TODO T-20)
    INSURANCE_OFFER,
    INSURANCE_CONFIRMED,
    INSURANCE_PREMIUM_OVERDUE,
    INSURANCE_CANCELLED,
    DAMAGE_NOTICE,
    INSURANCE_CLAIM_SETTLED,
    INSURANCE_CLAIM_REJECTED,
    // hunting (TODO T-20)
    WILDLIFE_DAMAGE_REPORTED,
    WILDLIFE_COUNTER,
    WILDLIFE_SETTLED,
    WILDLIFE_DISPUTE,
    // livestock (TODO T-20)
    VET_VISIT,
    LIVESTOCK_OFFER,
    LIVESTOCK_PREMIUM_PAID,
    LIVESTOCK_OFFER_LAPSED,
    BREEDING_ADVICE,
    // TODO T-22 lease
    LEASE_OFFER,
    LEASE_REFUSED,
    LEASE_CONFIRMED,
    LEASE_ENDING,
    LEASE_RENEWED,
    LEASE_PURCHASED,
    LEASE_RENT_OVERDUE,
    LEASE_ENDED,
    // TODO T-22 maintenance
    MAINTENANCE_OFFER,
    MAINTENANCE_CONFIRMED,
    MAINTENANCE_REPAIRED,
    MAINTENANCE_FEE_OVERDUE,
    MAINTENANCE_CANCELLED,
    REPAIR_HINT,
    // TODO T-22 contractor
    MISSION_REFERRAL,
    MISSION_THANKS,
    MISSION_FAILED,
    // Roadmap V3 R3-H: trade and contracts of the neighbours
    GOODS_OFFER,
    GOODS_REQUEST,
    GOODS_TRADE_DONE,
    GOODS_REQUEST_FAILED,
    NEIGHBOR_MISSION_REQUEST,
    NEIGHBOR_MISSION_THANKS,
    NEIGHBOR_MISSION_DISAPPOINTED,
    // Roadmap V3 R3-K: loan collateral, liquidity plan, farm report and annual review
    COLLATERAL_SALE_CONSENT,
    COLLATERAL_CLAIM,
    COLLATERAL_CLAIM_OVERDUE,
    CREDIT_COLLATERAL_REALISED,
    LIQUIDITY_WARNING,
    ANNUAL_REVIEW_INVITATION,
    ANNUAL_REVIEW_OFFER,
    ANNUAL_REVIEW_NEUTRAL,
    ANNUAL_REVIEW_SERIOUS,
    // Roadmap V3 R3-M: price alarm, forward contracts, farm shop
    PRICE_ALARM,
    FORWARD_CONTRACT_FULFILLED,
    FORWARD_CONTRACT_SHORTFALL,
    FARM_SHOP_ORDER,
    // Roadmap V3 R3-W: drought, drought aid, weather-index insurance
    DROUGHT_WARNING,
    DROUGHT_DECLARED,
    DROUGHT_AID_OFFER,
    DROUGHT_INSURANCE_OFFER,
    DROUGHT_INSURANCE_PAYOUT,
    // Roadmap V3 R3-V: used machines
    VEHICLE_OFFER,
    VEHICLE_SALE_OFFER,
    VEHICLE_DEAL_AGREED,
    VEHICLE_NO_SPACE,
    VEHICLE_DEAL_FAILED,
    VEHICLE_SOLD_GOSSIP,
    // Roadmap V3 R3-P: office clerk and apprentice
    OFFICE_CLERK_REMINDER,
    OFFICE_CLERK_PAID,
    APPRENTICE_TAKEOVER_REQUEST,
    APPRENTICE_TAKEN_OVER,
    APPRENTICE_LEAVES,
    // conversation
    REPLY,
    CALL_CONVERSATION
}
